Update strings_tr-TR.i18n.yaml
nullxception/boorusphere pull request #100
Opened 2023-03-02 22:11 UTC by kyoyacchi

Updated new strings and fixed some mistranslated strings. + Some grammar..

2023-03-02 22:15 UTC, kyoyacchi commented
I wonder what have i done wrong?

2023-03-02 23:21 UTC, nullxception commented
> I wonder what have i done wrong?

looks like you give the "blur_timeline_only:" too much tab/space, not aligned with other section. check the line 180.

2023-03-02 23:45 UTC, nullxception requested changes

2023-03-02 23:45 UTC, nullxception commented on lib/presentation/i18n/strings_tr-TR.i18n.yaml
> +    blur_timeline_only:
this one need to be aligned with blur_content or ime_incognito

2023-03-03 12:00 UTC, nullxception commented
I'll merge it anyway since it was a small mistake, Thanks!

2023-03-03 12:00 UTC, merged